name: NodeJS SDK Wrapper CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
  PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
  LT_SDK_DEBUG: true
  SMARTUI_DEBUG: true

jobs:
  smartui-nodejs-sdk:
    name: Execute NodeJS sdk build
    runs-on: ubuntu-latest
    steps:
      - name: Step for push event
        run: |
          echo "This is a push event!"
          echo "The latest commitId $(git log -1 --format='%H')"
          echo "COMMIT_ID=$(git log -1 --format='%H')" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Step for pull_request event
        run: |
          echo "This is a pull_request event!"
          git log -n 5 --format="%H %an %s" | while read line; do echo "$line"; done
          echo "The latest commitId $(git log -n 2 --format='%H' | tail -n 1)"
          echo "COMMIT_ID=$(git log -n 2 --format='%H' | tail -n 1)" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'
        
      - name: Checkout code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Create Github URL
        run: |
          API_HOST=https://api.github.com
          echo "The latest commitId is $COMMIT_ID"
          GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
          echo "GITHUB_URL: $GITHUB_URL"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV


      - name: Install Dependencies
        run: |
          npm i @lambdatest/smartui-cli

      - name: Execute NodeJS Wrapper
        run: |
          cd sdk
          npm i
          npx playwright install
          npx smartui --version
          npx smartui config:create smartui-web.json
          npm run smartui-cloud
